import { jsPDF } from "jspdf";
import { BusinessPlan } from "./types";

export function generateBusinessPlanPDF(plan: BusinessPlan) {
  // Create instance of jsPDF (A4 Portrait, measurements in millimeters)
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth(); // 210mm
  const pageHeight = doc.internal.pageSize.getHeight(); // 297mm
  const margin = 20;
  const contentWidth = pageWidth - margin * 2; // 170mm

  let currentPage = 1;

  // --- HELPER TO MANAGE PAGES & COORDINATES ---
  let y = 30;

  function checkPageBreak(neededHeight: number) {
    if (y + neededHeight > pageHeight - 25) {
      drawFooter();
      doc.addPage();
      currentPage++;
      y = 25;
      drawHeader();
    }
  }

  function drawHeader() {
    doc.setFont("Helvetica", "oblique");
    doc.setFontSize(8);
    doc.setTextColor(115, 115, 115); // Neutral 500
    doc.text(`Business Plan: ${plan.businessName}`, margin, 15);
    doc.line(margin, 17, pageWidth - margin, 17);
    y = 25;
  }

  function drawFooter() {
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(115, 115, 115);
    doc.text(`Page ${currentPage}`, pageWidth - margin - 15, pageHeight - 12);
    doc.text("Generated by AI Business Plan Workspace", margin, pageHeight - 12);
  }

  // --- COVER PAGE DESIGN ---
  // Background style element: a left margin border bar in slate
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 12, pageHeight, "F");

  // Title
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(15, 23, 42);
  doc.text("BUSINESS PLAN", 25, 75);

  // Business Name
  doc.setFontSize(22);
  doc.setTextColor(2, 132, 199); // sky-600
  doc.text(plan.businessName.toUpperCase(), 25, 90);

  // Divider
  doc.setDrawColor(2, 132, 199);
  doc.setLineWidth(1.5);
  doc.line(25, 98, 120, 98);

  // Subtitle Metadata
  doc.setLineWidth(0.2);
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(71, 85, 105); // slate-600
  
  let metadataY = 120;
  doc.setFont("Helvetica", "bold");
  doc.text("Niche & Industry:", 25, metadataY);
  doc.setFont("Helvetica", "normal");
  const nicheWrapped = doc.splitTextToSize(plan.niche, contentWidth - 30);
  doc.text(nicheWrapped, 65, metadataY);
  metadataY += (nicheWrapped.length * 5) + 3;

  doc.setFont("Helvetica", "bold");
  doc.text("Target Audience:", 25, metadataY);
  doc.setFont("Helvetica", "normal");
  const audienceWrapped = doc.splitTextToSize(plan.targetAudience, contentWidth - 30);
  doc.text(audienceWrapped, 65, metadataY);
  metadataY += (audienceWrapped.length * 5) + 3;

  doc.setFont("Helvetica", "bold");
  doc.text("Geographic Scope:", 25, metadataY);
  doc.setFont("Helvetica", "normal");
  doc.text(plan.location || "N/A", 65, metadataY);
  metadataY += 8;

  doc.setFont("Helvetica", "bold");
  doc.text("Business Stage:", 25, metadataY);
  doc.setFont("Helvetica", "normal");
  doc.text(plan.stage || "N/A", 65, metadataY);
  metadataY += 8;

  doc.setFont("Helvetica", "bold");
  doc.text("Launch Timeline:", 25, metadataY);
  doc.setFont("Helvetica", "normal");
  doc.text(plan.timeline || "N/A", 65, metadataY);
  metadataY += 8;

  // Bottom Branding / Date
  doc.setFont("Helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("PREPARED BY:", 25, pageHeight - 45);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor(71, 85, 105);
  doc.text("AI Strategy Planner Engine", 25, pageHeight - 39);
  doc.text(`Date: ${new Date(plan.createdAt).toLocaleDateString()}`, 25, pageHeight - 33);

  // Footer for cover
  drawFooter();

  // --- CONTENT PAGES ---
  doc.addPage();
  currentPage++;
  y = 25;
  drawHeader();

  // --- GENERAL TEXT WRITER ---
  function writeParagraph(title: string, text: string) {
    checkPageBreak(15);
    
    // Sub-heading
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.text(title, margin, y);
    y += 5;

    // Body
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85); // slate-700
    const lines = doc.splitTextToSize(text, contentWidth);
    
    for (const line of lines) {
      checkPageBreak(5);
      doc.text(line, margin, y);
      y += 5.5;
    }
    y += 4; // padding after paragraph
  }

  function writeSectionHeader(title: string) {
    checkPageBreak(25);
    y += 4;
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(2, 132, 199); // sky-600
    doc.text(title.toUpperCase(), margin, y);
    
    // Bottom border under Section Title
    y += 2.5;
    doc.setDrawColor(2, 132, 199);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageWidth - margin, y);
    y += 7;
  }

  function writeBulletList(title: string, items: string[]) {
    checkPageBreak(15);
    
    // Sub-heading
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text(title, margin, y);
    y += 5.5;

    // Bullets
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85);

    for (const item of items) {
      const bulletText = `•  ${item}`;
      const lines = doc.splitTextToSize(bulletText, contentWidth - 6);
      
      for (let i = 0; i < lines.length; i++) {
        checkPageBreak(5);
        // Indent consecutive wrapped lines
        const indent = i === 0 ? margin : margin + 4;
        doc.text(lines[i], indent, y);
        y += 5;
      }
      y += 1.5; // spacing between bullets
    }
    y += 3; // padding after list
  }

  // ==================== SECTION 1: EXECUTIVE SUMMARY ====================
  writeSectionHeader("1. Executive Summary");
  writeParagraph("Mission Statement", plan.executiveSummary.mission);
  writeParagraph("Vision Statement", plan.executiveSummary.vision);
  writeParagraph("Problem Statement (Market Pain Points)", plan.executiveSummary.problemSolved);
  writeParagraph("Solution & Core Value Proposition", plan.executiveSummary.solution);
  writeBulletList("Key Factors for Success", plan.executiveSummary.keySuccessFactors);

  // ==================== SECTION 2: MARKET ANALYSIS ====================
  writeSectionHeader("2. Market & Target Audience Analysis");
  writeParagraph("Target Audience Segment Profile", plan.marketAnalysis.audienceProfile);
  writeParagraph("Competitor Landscape & Competitive Advantage", plan.marketAnalysis.competitorAnalysis);
  writeParagraph("Key Market & Industry Trends", plan.marketAnalysis.marketTrends);
  
  // SWOT matrix
  checkPageBreak(55);
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text("SWOT Analysis Matrix", margin, y);
  y += 6;

  // Let's print SWOT items cleanly
  const swot = plan.marketAnalysis.swotAnalysis;
  writeBulletList("Internal Strengths (+)", swot.strengths);
  writeBulletList("Internal Weaknesses (-)", swot.weaknesses);
  writeBulletList("External Opportunities (▲)", swot.opportunities);
  writeBulletList("External Threats (▼)", swot.threats);

  // ==================== SECTION 3: MARKETING & SALES ====================
  writeSectionHeader("3. Marketing & Sales Strategy");
  writeParagraph("Brand Positioning Strategy", plan.marketingStrategy.positioning);
  writeParagraph("Pricing Model & Rationale", plan.marketingStrategy.pricingModel);
  writeBulletList("Primary Marketing Channels", plan.marketingStrategy.marketingChannels);
  writeParagraph("Sales Conversion & Funnel Tactic", plan.marketingStrategy.salesTactic);

  // ==================== SECTION 4: OPERATIONS PLAN ====================
  writeSectionHeader("4. Operational Infrastructure");
  writeParagraph("Core Operational Activities", plan.operationsPlan.keyOperations);
  writeBulletList("Technology & Resource Requirements", plan.operationsPlan.technologyRequirements);
  writeParagraph("Personnel & Human Resource Structure", plan.operationsPlan.personnelNeeds);

  // ==================== SECTION 5: FINANCIAL PLAN ====================
  writeSectionHeader("5. Financial Outlook & Objectives");
  writeBulletList("Primary Revenue Streams", plan.financialOutlook.revenueStreams);
  writeBulletList("Key Cost Structure Categories", plan.financialOutlook.costStructure);
  writeParagraph("Break-Even & Profitability Timeline", plan.financialOutlook.breakEvenAnalysis);
  writeParagraph("Initial Capital & Funding Goals", plan.financialOutlook.fundingGoal);

  // Draw final footer
  drawFooter();

  // Save/Download PDF
  const filename = `${plan.businessName.replace(/\s+/g, "_")}_Business_Plan.pdf`;
  doc.save(filename);
}
